apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pulls everything from base
resources:
  - ../../base

namespace: dev-apps

images:
  - name: pertra/express-docker-app-jenkins
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: guestbook-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: Host(`demo-i.local`)