apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pulls everything from base
resources:
  - ../../base

namespace: qa-apps

images:
  - name: pertra/express-docker-app-jenkins
    newTag: latest 

patches:
  - target:
        kind: Deployment
        name: api-app1-app 
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ "name": "private-registry-secret" }]
  - target:
      kind: Ingress
      name: guestbook-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: Host(`demo-ii.local`)